### ISSUE TITLE
Вынести вычисление в отдельную функции

### ISSUE THREAD

**Issue by tardis-forever** [TheNeonLightning/Algorithm_3Sem#1]
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/6a7bc18c6f72be74bd20b82aea85830113d2728e/Module1_Task1/main.cpp#L23

Btw, '(в описаниях алгоритма обычно обозначается как j)' - скорее засоряющий код тип комментариев

**Comment by TheNeonLightning** [comment]
Разбил код на несколько функций, избавился от лишнего копирования.
В контест снова отправил: https://contest.yandex.ru/contest/13875/problems/?success=21379502#194179/2016_11_19/Kprz2MtoeI
