### ISSUE TITLE
could prefix_function <> be const?

### ISSUE THREAD

**Issue by tardis-forever** [TheNeonLightning/Algorithm_3Sem#3]
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/97e49875b642f3627c62649aedf4cb50a0b21af5/Module1_Task1/main.cpp#L36

**Comment by tardis-forever** [comment]
а также длинные строки стоит разбить переносами на несколько более коротких

**Comment by TheNeonLightning** [comment]
Исправил: https://github.com/TheNeonLightning/Algorithm_3Sem/commit/d30917eb420597996eb715cee52251ad7a4e2e21
Контест: https://contest.yandex.ru/contest/13875/run-report/21489257/
Извиняюсь за большое количество лишних фаилов, забыл добавить gitignore. В следующий раз буду предусмотрителен.
