### ISSUE TITLE
Лучше for с заранее видными границами, чем while(true)

### ISSUE THREAD

**Issue by tardis-forever** [TheNeonLightning/Algorithm_3Sem#4]
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/3f9f25c012aa22268493c04a7de889656dde79a0/Module1_Task2/main.cpp#L49

**Comment by TheNeonLightning** [comment]
Исправил,
commit: 7a67e17fcdb7af57a211617bd808edfb3ab6bf7c
контест: https://contest.yandex.ru/contest/13875/run-report/21645236/

**Comment by TheNeonLightning** [comment]
Извиняюсь, прикрепил не тот коммит. Вот нужный: 3cc9477054134a9e789a41a2d2e427ca865c91bb
