### ISSUE TITLE
слишком длинная функция, рабить на несколько составных блоков

### ISSUE THREAD

**Issue by tardis-forever** [TheNeonLightning/Algorithm_3Sem#6]
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/d9472d797c5ac389ba8f44c0a0137e1b5ffa9561/Module1_Task3/main.cpp#L158

**Comment by TheNeonLightning** [comment]
Исправил:
контест: https://contest.yandex.ru/contest/13875/run-report/22859407/
commit: 3a19db4d5688cadb05f9158565e226f612b9e6f2
