### ISSUE TITLE
1e-9

### ISSUE THREAD

**Issue by tardis-forever** [TheNeonLightning/Algorithm_3Sem#7]
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/d5236376f576fcec5c08ccfacf1bfeb824059408/Module3_Task1/main.cpp#L8

**Comment by TheNeonLightning** [comment]
Исправлено: https://github.com/TheNeonLightning/Algorithm_3Sem/commit/64b71eab7abcd8d1d6a1dc416efae6a90fca6e8b
