### ISSUE TITLE
на первый можно навесить const qualifier

### ISSUE THREAD

**Issue by tardis-forever** [TheNeonLightning/Algorithm_3Sem#8]
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/109c6d96f3bcba8e5405e9bada3905706f6db60a/Module3_Task3/main.cpp#L205

и вообще, const должен быть везде, где только можно

**Comment by tardis-forever** [comment]
а почему в классе осталось?
https://github.com/TheNeonLightning/Algorithm_3Sem/blob/046861b24c2970417f65f396233410b4e542c908/Module3_Task3/main.cpp#L49

**Comment by TheNeonLightning** [comment]
Убрал const из объявления, потому что достаточно const в реализации ставить. Хотя конечно нужно было и в объявлении написать, чтобы было проще читать. Исправил.
